;* Generated by appData/src/snes/tools/gen-dummy-gfx.js. Do not edit.
.include "hdr.asm"

.include "src/data/bg0_data.as"
.include "src/data/bg1_data.as"
.include "src/data/uifont_data.as"
.include "src/data/scene_spr_0_data.as"
.include "src/data/scene_spr_pal_0_data.as"
