#ifndef ASSETS_H
#define ASSETS_H

/* Generated by appData/src/snes/tools/gen-dummy-gfx.js. Do not edit. */
#include "gbs_types.h"

extern const unsigned char scene_spr_0[8192];
extern const unsigned char *const scene_spr_ptrs[2];
extern const unsigned char *const scene_spr_pal_ptrs[2];
extern const unsigned char *const scene_sprite_slot_ptrs[2];
extern const unsigned char ui_font[3760];
extern const unsigned char ui_pal[8];

extern const unsigned char *const bg_tiles_ptrs[2];
extern const unsigned char *const bg_maps_ptrs[2];
extern const unsigned char *const bg_pals_ptrs[2];
extern const unsigned short bg_tiles_len[2];
extern const unsigned short bg_maps_len[2];
extern const unsigned short bg_pals_len[2];
extern const unsigned char bg_map_w[2];
extern const unsigned char bg_map_h[2];

extern const BANK_PTR event_ptrs[];
extern const BANK_PTR string_ptrs[];
extern const unsigned char *const scenes[];

#define NUM_SCENES 2
#define NUM_BGS 2
#define NUM_SPRITE_SHEETS 1
#define SPRITE_SLOTS 8
#define SPR_TILES_SIZE 8192
#define SPR_PAL_SIZE   256
#define UI_FONT_SIZE  3760
#define UI_PAL_SIZE   8
#define NUM_UI_GLYPHS 224
#define UI_FILL_TILE  224
#define UI_FRAME_TILE0 225
#define UI_CURSOR_TILE 234
#define EMOTE_TILE0 32
#define NUM_EMOTES 8
#define AVATAR_TILE0 64
#define NUM_AVATARS 1
#define ACTOR_UP_TILE0 96
#define ACTOR_SIDE_TILE0 128
#define ACTOR_DOWN_B_TILE0 160
#define ACTOR_UP_B_TILE0 192
#define ACTOR_SIDE_B_TILE0 224
#define NUM_STRINGS   8
#define START_SCENE 0
#define START_X 10
#define START_Y 20
#define START_DIR 1
#define PLAYER_SPRITE_SLOT 0
#define PLAYER_SPRITE_TYPE 0
#define PLAYER_SPRITE_PAL 0
#define PLAYER_ANIM_SPEED 3
#define NUM_MUSIC_TRACKS 1

#endif
