/* Generated by appData/src/snes/tools/gen-dummy-gfx.js from
 * appData/src/snes/engine.json - see compileSnesData.js's real
 * equivalent, compileEngineFields, for how a real project build
 * differs (project-chosen Settings values instead of defaultValue). */
#include "gbs_types.h"

u8 topdown_grid = 8;
s16 plat_min_vel = 304;
s16 plat_walk_vel = 6400;
s16 plat_run_vel = 10496;
s16 plat_walk_acc = 152;
s16 plat_run_acc = 228;
s16 plat_dec = 208;
s16 plat_jump_vel = 16384;
s16 plat_grav = 1792;
s16 plat_hold_grav = 512;
s16 plat_max_fall_vel = 20000;
u8 shooter_scroll_speed = 1;
