/*
 * gen-sfx.js - the SNES engine's built-in sound effects.
 *
 * GB Studio 1.2.2 has no per-project sound-effect assets; its SOUND_* events
 * (Play Beep / Play Tone / Play Crash) are synthesised on Game Boy hardware.
 * The SNES engine plays short BRR samples instead, streamed through PVSnesLib's
 * snesmod BRR sound region (spcAllocateSoundRegion / spcPlaySound) so they
 * layer over the music instead of interrupting it.
 *
 * This script synthesises two tiny mono 16-bit PCM waveforms and encodes them
 * to BRR with the vendored `snesbrr` tool:
 *   sfx_beep.brr  - a short square-wave blip (Play Beep, Play Tone)
 *   sfx_crash.brr - a short burst of decaying noise (Play Crash)
 * It writes res/sfx_*.{wav,brr} + res/sfx.h (byte lengths). The .wav files are
 * the source of truth; the .brr + .h are committed so a plain `make` eject
 * doesn't need snesbrr. Re-run this if you change the waveforms.
 */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const RES = path.resolve(__dirname, "..", "res");
const EXT = process.platform === "win32" ? ".exe" : "";
const SNESBRR = path.resolve(
  __dirname,
  `../../../../buildTools/${process.platform}-${process.arch}/pvsneslib/devkitsnes/tools/snesbrr${EXT}`
);

// mono 16-bit PCM WAV. snesbrr ignores the sample rate (playback rate is set at
// play time via the BRR pitch), so the number here is cosmetic.
function writeWav(file, samples, sampleRate = 8000) {
  const data = Buffer.alloc(samples.length * 2);
  for (let i = 0; i < samples.length; i++) {
    let s = Math.round(samples[i]);
    if (s > 32767) s = 32767;
    if (s < -32768) s = -32768;
    data.writeInt16LE(s, i * 2);
  }
  const header = Buffer.alloc(44);
  header.write("RIFF", 0);
  header.writeUInt32LE(36 + data.length, 4);
  header.write("WAVE", 8);
  header.write("fmt ", 12);
  header.writeUInt32LE(16, 16); // PCM chunk size
  header.writeUInt16LE(1, 20); // PCM
  header.writeUInt16LE(1, 22); // mono
  header.writeUInt32LE(sampleRate, 24);
  header.writeUInt32LE(sampleRate * 2, 28); // byte rate
  header.writeUInt16LE(2, 32); // block align
  header.writeUInt16LE(16, 34); // bits
  header.write("data", 36);
  header.writeUInt32LE(data.length, 40);
  fs.writeFileSync(file, Buffer.concat([header, data]));
}

// A square wave (8-sample period) with a short linear decay - a clean retro
// "blip". Length is a multiple of 16 (one BRR block) so nothing is padded.
function beep() {
  const N = 512;
  const out = new Array(N);
  for (let i = 0; i < N; i++) {
    const env = 1 - i / N;
    out[i] = (i % 8 < 4 ? 1 : -1) * 9000 * env;
  }
  return out;
}

// Decaying pseudo-noise (a deterministic LFSR so the file is reproducible).
function crash() {
  const N = 1024;
  const out = new Array(N);
  let lfsr = 0x7f2a;
  for (let i = 0; i < N; i++) {
    lfsr = ((lfsr >> 1) ^ (-(lfsr & 1) & 0xb400)) & 0xffff;
    const env = (1 - i / N) ** 2;
    out[i] = ((lfsr & 0x1fff) - 0x1000) * 2.4 * env;
  }
  return out;
}

function encode(name, samples) {
  const wav = path.join(RES, `${name}.wav`);
  const brr = path.join(RES, `${name}.brr`);
  writeWav(wav, samples);
  execFileSync(SNESBRR, ["-e", wav, brr], { stdio: "inherit" });
  return fs.statSync(brr).size;
}

fs.mkdirSync(RES, { recursive: true });
const beepLen = encode("sfx_beep", beep());
const crashLen = encode("sfx_crash", crash());

fs.writeFileSync(
  path.join(RES, "sfx.h"),
  `/* Generated by appData/src/snes/tools/gen-sfx.js. Byte lengths of the
 * built-in BRR sound effects (music.c passes these to spcSetSoundEntry). */
#ifndef SFX_H
#define SFX_H

#define SFX_BEEP_LEN  ${beepLen}
#define SFX_CRASH_LEN ${crashLen}

#endif
`
);

console.log(`sfx_beep.brr ${beepLen} B, sfx_crash.brr ${crashLen} B, wrote res/sfx.h`);
