/*
 * compileSnesMusic.js - M8 phase 2: a project's own `.mod` songs -> the SNES
 * snesmod soundbank the engine plays.
 *
 * Pipeline: each project `.mod` -> `mod2it.js` -> a temp `.it` -> `smconv -s`
 * builds one soundbank from the vendored effect module (`res/effectssfx.it`,
 * always soundbank module 0) followed by the project songs (modules 1..N). The
 * resulting `.bnk` replaces the ejected tree's `res/soundbank.bnk`; a
 * hand-written `src/res/soundbank.asm` `.incbin`s it (same layout as the M8
 * phase 1 committed one - see appData/src/snes/README.md for why the `.asm`
 * lives under `src/`). `music.c` plays song `track` via `spcLoad(1 + track)`.
 *
 * No project music -> this is a no-op and the ejected tree keeps its committed
 * proof-of-concept soundbank (effects + one demo track).
 */
import childProcess from "child_process";
import fs from "fs-extra";
import Path from "path";
import { assetFilename } from "../helpers/gbstudio";
import { pathExists } from "../helpers/fsCopy";
import { resolvePvsHome } from "./buildSnesRom";
import { modToIt } from "./mod2it";

const run = (cmd, args, cwd) =>
  new Promise((resolve, reject) => {
    const child = childProcess.spawn(cmd, args, { cwd, shell: false });
    let out = "";
    child.stdout.on("data", d => {
      out += d.toString();
    });
    child.stderr.on("data", d => {
      out += d.toString();
    });
    child.on("error", reject);
    child.on("close", code =>
      code === 0
        ? resolve(out)
        : reject(new Error(`smconv failed (exit ${code})\n${out.trim()}`))
    );
  });

// smconv emits res/soundbank.asm with an absolute `.incbin` path and, when the
// soundbank is larger than one 32 KB LoROM bank, splits it into
// SOUNDBANK__0 / SOUNDBANK__1 / ... sections on consecutive banks (5, 6, ...).
// Normalise the `.incbin` path to the tree-relative `res/soundbank.bnk` the
// committed engine expects (so a `make` eject resolves it too), and count the
// SOUNDBANK__ symbols so music.c can spcSetBank() each chunk.
const normaliseSoundbankAsm = asm => {
  const fixed = asm.replace(
    /\.incbin\s+"[^"]*soundbank\.bnk"/g,
    '.incbin "res/soundbank.bnk"'
  );
  const single = /^SOUNDBANK__:/m.test(fixed);
  const numbered = (fixed.match(/^SOUNDBANK__\d+:/gm) || []).length;
  const bankCount = single ? 1 : numbered;
  return { asm: fixed, bankCount };
};

// The companion header music.c includes: the extern decls for however many
// SOUNDBANK__ chunks smconv produced + a MUSIC_SET_BANKS() that registers them
// with snesmod (reverse order, so chunk 0 ends up first - matches PVSnesLib's
// own musicGreaterThan32k example).
const soundbankBanksHeader = bankCount => {
  const lines = [
    "// generated by compileSnesMusic.js - extern decls for the soundbank",
    "// chunks smconv laid into ROM, plus the spcSetBank() sequence for them.",
    "#ifndef __SOUNDBANK_BANKS__",
    "#define __SOUNDBANK_BANKS__",
    ""
  ];
  if (bankCount <= 1) {
    lines.push("extern char SOUNDBANK__;");
    lines.push("#define MUSIC_SET_BANKS() spcSetBank(&SOUNDBANK__)");
  } else {
    const names = [];
    for (let i = 0; i < bankCount; i++) names.push(`SOUNDBANK__${i}`);
    lines.push(`extern char ${names.join(", ")};`);
    const calls = names
      .slice()
      .reverse()
      .map(n => `spcSetBank(&${n})`)
      .join("; ");
    lines.push(`#define MUSIC_SET_BANKS() do { ${calls}; } while (0)`);
  }
  lines.push("", "#endif // __SOUNDBANK_BANKS__", "");
  return lines.join("\n");
};

const compileSnesMusic = async ({
  music = [],
  projectRoot,
  buildRoot = "/tmp",
  progress = () => {},
  warnings = () => {}
} = {}) => {
  if (music.length === 0) {
    return; // keep the committed proof-of-concept soundbank
  }

  const pvsHome = await resolvePvsHome({ progress });
  const ext = process.platform === "win32" ? ".exe" : "";
  const smconv = Path.join(pvsHome, "devkitsnes", "tools", `smconv${ext}`);

  const workDir = Path.join(buildRoot, "obj", "music");
  await fs.ensureDir(workDir);
  await fs.ensureDir(Path.join(buildRoot, "res"));
  await fs.ensureDir(Path.join(buildRoot, "src", "res"));

  const effectsIt = Path.join(buildRoot, "res", "effectssfx.it");
  if (!(await pathExists(effectsIt))) {
    warnings("compileSnesMusic: res/effectssfx.it missing from the engine tree");
    return;
  }

  // .mod -> .it for one track. smconv assigns soundbank module numbers by
  // argument position and the engine plays track N as module (1 + N), so the
  // list must stay 1:1 with project order: a track that can't be read/converted
  // falls back to the (valid) effects module rather than shifting every later
  // track's index.
  const convertTrack = async (track, i) => {
    let modBuf;
    try {
      modBuf = await fs.readFile(assetFilename(projectRoot, "music", track));
    } catch (e) {
      warnings(
        `Music track "${track.filename}" not found - it will be silent in-game`
      );
      return effectsIt;
    }
    try {
      const itPath = Path.join(workDir, `mus${i}.it`);
      await fs.writeFile(itPath, modToIt(modBuf));
      progress(`Converted music ${track.name || track.filename}`);
      return itPath;
    } catch (e) {
      warnings(
        `Could not convert "${track.filename}" to .it (${e.message}) - it will be silent in-game`
      );
      return effectsIt;
    }
  };

  const itFiles = [effectsIt];
  for (let i = 0; i < music.length; i++) {
    itFiles.push(await convertTrack(music[i], i));
  }

  progress("Building soundbank (smconv)");
  await run(
    smconv,
    ["-s", "-o", Path.join(workDir, "soundbank"), "-b", "5", ...itFiles],
    workDir
  );

  await fs.copy(
    Path.join(workDir, "soundbank.bnk"),
    Path.join(buildRoot, "res", "soundbank.bnk")
  );
  await fs.copy(
    Path.join(workDir, "soundbank.h"),
    Path.join(buildRoot, "res", "soundbank.h")
  );

  const { asm, bankCount } = normaliseSoundbankAsm(
    await fs.readFile(Path.join(workDir, "soundbank.asm"), "utf8")
  );
  await fs.writeFile(Path.join(buildRoot, "src", "res", "soundbank.asm"), asm);
  await fs.writeFile(
    Path.join(buildRoot, "res", "soundbank_banks.h"),
    soundbankBanksHeader(bankCount)
  );

  const firstFreeBank = 5;
  if (firstFreeBank + bankCount > 8) {
    warnings(
      `Soundbank needs ${bankCount} ROM banks (5..${firstFreeBank +
        bankCount -
        1}); the SNES ROM only has 8. Reduce music or shorten samples.`
    );
  }
  progress(
    `Soundbank built (${itFiles.length - 1} track(s), ${bankCount} ROM bank(s))`
  );
};

export default compileSnesMusic;
