/* Generated by appData/src/snes/tools/gen-sfx.js. Byte lengths of the
 * built-in BRR sound effects (music.c passes these to spcSetSoundEntry). */
#ifndef SFX_H
#define SFX_H

#define SFX_BEEP_LEN  297
#define SFX_CRASH_LEN 585

#endif
